---
clickhouse:
  hosts:
    clickhouse:
      ansible_host: 51.250.23.93
      ansible_user: fe1br0

vector:
  hosts:
    vector:
      ansible_host: 130.193.52.42
      ansible_user: fe1br0

lighthouse:
  hosts:
    lighthouse:
      ansible_host: 51.250.97.255
      ansible_user: fe1br0
